language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls lxml nose requests six
script:
  - coverage run --source=chemspipy setup.py test
after_success:
  - coveralls
